name: CI

on: [push]

jobs:
  build:
    name: Lint, Test, Build & Pack on Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20.x']

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Pack
        run: npm pack

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./package.tgz

  test-dist:
    name: Test against dist
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['20.x']
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: package
          path: .

      - name: Install build artifact
        run: npm install ./package.tgz

      - name: Run tests
        run: npm test

  test-types:
    name: Test types with TypeScript ${{ matrix.ts }}

    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['20.x']
        ts: ['4.7', '4.8', '4.9', '5.0', '5.1', '5.2', '5.3', '5.4']
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Install TypeScript ${{ matrix.ts }}
        run: npm install typescript@~${{ matrix.ts }}

      - uses: actions/download-artifact@v4
        with:
          name: package
          path: .

      - name: Install build artifact
        run: npm install ./package.tgz

      - name: Test types
        run: |
          npx tsc --version
          npm run test:types

  are-the-types-wrong:
    name: Check package config with are-the-types-wrong

    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['20.x']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm install

      - uses: actions/download-artifact@v4
        with:
          name: package
          path: .

      - name: Run are-the-types-wrong
        run: npx @arethetypeswrong/cli -P .
